# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |kiota| "https://rubygems.pkg.github.com/microsoft" }

# gem "rails"

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_abstractions", "0.1.3"
end

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_serialization", "0.1.1"
end

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_nethttp", "0.1.0"
end

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'rubocop', require: false

gem 'concurrent-ruby', '~> 1.1', '>= 1.1.9'

gem 'ruby-debug-ide'