// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota

export interface MessageItemRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[] | undefined;
    /**
     * Select properties to be returned
     */
    select?: string[] | undefined;
}
// tslint:enable
// eslint-enable
