# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |kiota| "https://rubygems.pkg.github.com/microsoft" }

# gem "rails"

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_abstractions", "0.3.0"
end

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_serialization", "0.3.0"
end

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_nethttplibrary", "0.2.0"
end

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_authentication_oauth", "0.2.0"
end

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'rubocop', require: false

gem 'ruby-debug-ide'