# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |kiota| "https://rubygems.pkg.github.com/microsoft" }

# gem "rails"

gem "microsoft_kiota_abstractions", "0.12.0"

gem "microsoft_kiota_serialization_json", "0.7.0"

gem "microsoft_kiota_faraday", "0.10.0"

# gem "microsoft_kiota_authentication_oauth", "0.2.0"

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'rubocop', require: false

gem 'ruby-debug-ide'