// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { deserializeIntoAttachment } from './deserializeIntoAttachment';
import { type Attachment } from './index';
import { type ParseNode } from '@microsoft/kiota-abstractions';

export function createAttachmentFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoAttachment;
}
// tslint:enable
// eslint-enable
