// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { deserializeIntoRecipient } from './deserializeIntoRecipient';
import { type Recipient } from './index';
import { type ParseNode } from '@microsoft/kiota-abstractions';

export function createRecipientFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoRecipient;
}
// tslint:enable
// eslint-enable
