// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { createInferenceClassificationOverrideFromDiscriminatorValue } from './createInferenceClassificationOverrideFromDiscriminatorValue';
import { type InferenceClassificationOverride } from './inferenceClassificationOverride';
import { type InferenceClassificationOverrideCollectionResponse } from './inferenceClassificationOverrideCollectionResponse';
import { serializeInferenceClassificationOverride } from './serializeInferenceClassificationOverride';
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function deserializeIntoInferenceClassificationOverrideCollectionResponse(inferenceClassificationOverrideCollectionResponse: InferenceClassificationOverrideCollectionResponse | undefined = {} as InferenceClassificationOverrideCollectionResponse) : Record<string, (node: ParseNode) => void> {
    return {
        "@odata.nextLink": n => { inferenceClassificationOverrideCollectionResponse.odataNextLink = n.getStringValue(); },
        "value": n => { inferenceClassificationOverrideCollectionResponse.value = n.getCollectionOfObjectValues<InferenceClassificationOverride>(createInferenceClassificationOverrideFromDiscriminatorValue); },
    }
}
// tslint:enable
// eslint-enable
