// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { createMessageRuleFromDiscriminatorValue } from './createMessageRuleFromDiscriminatorValue';
import { type MessageRule } from './messageRule';
import { type MessageRuleCollectionResponse } from './messageRuleCollectionResponse';
import { serializeMessageRule } from './serializeMessageRule';
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function deserializeIntoMessageRuleCollectionResponse(messageRuleCollectionResponse: MessageRuleCollectionResponse | undefined = {} as MessageRuleCollectionResponse) : Record<string, (node: ParseNode) => void> {
    return {
        "@odata.nextLink": n => { messageRuleCollectionResponse.odataNextLink = n.getStringValue(); },
        "value": n => { messageRuleCollectionResponse.value = n.getCollectionOfObjectValues<MessageRule>(createMessageRuleFromDiscriminatorValue); },
    }
}
// tslint:enable
// eslint-enable
