// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Entity } from './entity';
import { type Parsable } from '@microsoft/kiota-abstractions';

export interface SingleValueLegacyExtendedProperty extends Entity, Parsable {
    /**
     * A property value.
     */
    value?: string | undefined;
}
// tslint:enable
// eslint-enable
