// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Graphdotnetv4.Models {
    public enum InferenceClassificationType
    {
        [EnumMember(Value = "focused")]
        Focused,
        [EnumMember(Value = "other")]
        Other,
    }
}
