// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type OverridesRequestBuilderGetQueryParameters } from './overridesRequestBuilderGetQueryParameters';
import { type RequestOption } from '@microsoft/kiota-abstractions';

export interface OverridesRequestBuilderGetRequestConfiguration {
    /**
     * Request headers
     */
    headers?: Record<string, string[]>;
    /**
     * Request options
     */
    options?: RequestOption[];
    /**
     * Request query parameters
     */
    queryParameters?: OverridesRequestBuilderGetQueryParameters;
}
// tslint:enable
// eslint-enable
