// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type CountRequestBuilderGetQueryParameters } from './countRequestBuilderGetQueryParameters';
import { type RequestOption } from '@microsoft/kiota-abstractions';

export interface CountRequestBuilderGetRequestConfiguration {
    /**
     * Request headers
     */
    headers?: Record<string, string[]> | undefined;
    /**
     * Request options
     */
    options?: RequestOption[] | undefined;
    /**
     * Request query parameters
     */
    queryParameters?: CountRequestBuilderGetQueryParameters | undefined;
}
// tslint:enable
// eslint-enable
