package models
type MessageRulePredicates struct {
    additionalData map[string]interface{};
    bodyContains []*string;
    bodyOrSubjectContains []*string;
    categories []*string;
    fromAddresses []Recipient;
    hasAttachments *bool;
    headerContains []*string;
    importance Importance;
    isApprovalRequest *bool;
    isAutomaticForward *bool;
    isAutomaticReply *bool;
    isEncrypted *bool;
    isMeetingRequest *bool;
    isMeetingResponse *bool;
    isNonDeliveryReport *bool;
    isPermissionControlled *bool;
    isReadReceipt *bool;
    isSigned *bool;
    isVoicemail *bool;
    messageActionFlag MessageActionFlag;
    notSentToMe *bool;
    recipientContains []*string;
    senderContains []*string;
    sensitivity Sensitivity;
    sentCcMe *bool;
    sentOnlyToMe *bool;
    sentToAddresses []Recipient;
    sentToMe *bool;
    sentToOrCcMe *bool;
    subjectContains []*string;
    withinSizeRange SizeRange;
}
