// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type MessageRuleItemRequestBuilderGetQueryParameters } from './messageRuleItemRequestBuilderGetQueryParameters';
import { type RequestOption } from '@microsoft/kiota-abstractions';

export interface MessageRuleItemRequestBuilderGetRequestConfiguration {
    /**
     * Request headers
     */
    headers?: Record<string, string[]>;
    /**
     * Request options
     */
    options?: RequestOption[];
    /**
     * Request query parameters
     */
    queryParameters?: MessageRuleItemRequestBuilderGetQueryParameters;
}
// tslint:enable
// eslint-enable
