source 'https://rubygems.org'
git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

gem 'microsoft_kiota_abstractions'
gem 'microsoft_kiota_serialization_json'
gem 'microsoft_kiota_authentication_oauth'
gem 'microsoft_kiota_faraday'

gem 'rake'
gem 'rspec'
gem 'webmock'
