    source 'https://rubygems.org'
    git_source(:github) { |repo_name| "https://rubygems.pkg.github.com/microsoft" }

    source "https://rubygems.pkg.github.com/microsoft" do
        gem "microsoft_kiota_abstractions"
        gem "microsoft_kiota_serialization"
        gem "microsoft_kiota_authentication_oauth"
        gem "microsoft_kiota_nethttplibrary"
    end