// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type RequestOption } from '@microsoft/kiota-abstractions';

export interface InferenceClassificationOverrideItemRequestBuilderPatchRequestConfiguration {
    /**
     * Request headers
     */
    headers?: Record<string, string[]>;
    /**
     * Request options
     */
    options?: RequestOption[];
}
// tslint:enable
// eslint-enable
