// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota

export interface InferenceClassificationRequestBuilderGetQueryParameters {
    /**
     * Select properties to be returned
     */
    select?: string[];
}
// tslint:enable
// eslint-enable
