// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type InferenceClassificationRequestBuilderGetQueryParameters } from './inferenceClassificationRequestBuilderGetQueryParameters';
import { type RequestOption } from '@microsoft/kiota-abstractions';

export interface InferenceClassificationRequestBuilderGetRequestConfiguration {
    /**
     * Request headers
     */
    headers?: Record<string, string[]>;
    /**
     * Request options
     */
    options?: RequestOption[];
    /**
     * Request query parameters
     */
    queryParameters?: InferenceClassificationRequestBuilderGetQueryParameters;
}
// tslint:enable
// eslint-enable
