// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type MailFolderItemRequestBuilderGetQueryParameters } from './mailFolderItemRequestBuilderGetQueryParameters';
import { type RequestOption } from '@microsoft/kiota-abstractions';

export interface MailFolderItemRequestBuilderGetRequestConfiguration {
    /**
     * Request headers
     */
    headers?: Record<string, string[]>;
    /**
     * Request options
     */
    options?: RequestOption[];
    /**
     * Request query parameters
     */
    queryParameters?: MailFolderItemRequestBuilderGetQueryParameters;
}
// tslint:enable
// eslint-enable
