// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type ExtensionItemRequestBuilderGetQueryParameters } from './extensionItemRequestBuilderGetQueryParameters';
import { type RequestOption } from '@microsoft/kiota-abstractions';

export interface ExtensionItemRequestBuilderGetRequestConfiguration {
    /**
     * Request headers
     */
    headers?: Record<string, string[]> | undefined;
    /**
     * Request options
     */
    options?: RequestOption[] | undefined;
    /**
     * Request query parameters
     */
    queryParameters?: ExtensionItemRequestBuilderGetQueryParameters | undefined;
}
// tslint:enable
// eslint-enable
