module Graphrubyv4 end
# module Graphrubyv4::Utilities end
# module Graphrubyv4::Utilities::Users end
# module Graphrubyv4::Utilities::Users::InferenceClassification end
# module Graphrubyv4::Utilities::Users::InferenceClassification::Overrides end
# module Graphrubyv4::Utilities::Users::InferenceClassification::Overrides::Item end
# module Graphrubyv4::Utilities::Users::Item end
# module Graphrubyv4::Utilities::Users::MailFolders end
# module Graphrubyv4::Utilities::Users::MailFolders::ChildFolders end
# module Graphrubyv4::Utilities::Users::MailFolders::ChildFolders::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::MessageRules end
# module Graphrubyv4::Utilities::Users::MailFolders::MessageRules::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::Attachments end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::Attachments::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::Content end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::Extensions end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::Extensions::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::MultiValueExtendedProperties end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::MultiValueExtendedProperties::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::SingleValueExtendedProperties end
# module Graphrubyv4::Utilities::Users::MailFolders::Messages::SingleValueExtendedProperties::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::MultiValueExtendedProperties end
# module Graphrubyv4::Utilities::Users::MailFolders::MultiValueExtendedProperties::Item end
# module Graphrubyv4::Utilities::Users::MailFolders::SingleValueExtendedProperties end
# module Graphrubyv4::Utilities::Users::MailFolders::SingleValueExtendedProperties::Item end
# module Graphrubyv4::Utilities::Users::Messages end
# module Graphrubyv4::Utilities::Users::Messages::Attachments end
# module Graphrubyv4::Utilities::Users::Messages::Attachments::Item end
# module Graphrubyv4::Utilities::Users::Messages::Content end
# module Graphrubyv4::Utilities::Users::Messages::Extensions end
# module Graphrubyv4::Utilities::Users::Messages::Extensions::Item end
# module Graphrubyv4::Utilities::Users::Messages::Item end
# module Graphrubyv4::Utilities::Users::Messages::MultiValueExtendedProperties end
# module Graphrubyv4::Utilities::Users::Messages::MultiValueExtendedProperties::Item end
# module Graphrubyv4::Utilities::Users::Messages::SingleValueExtendedProperties end
# module Graphrubyv4::Utilities::Users::Messages::SingleValueExtendedProperties::Item end