// <auto-generated/>
using Graphdotnetv4.Users.Item.InferenceClassification;
using Graphdotnetv4.Users.Item.MailFolders;
using Graphdotnetv4.Users.Item.Messages;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Graphdotnetv4.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \users\{user-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class UserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The inferenceClassification property</summary>
        public global::Graphdotnetv4.Users.Item.InferenceClassification.InferenceClassificationRequestBuilder InferenceClassification
        {
            get => new global::Graphdotnetv4.Users.Item.InferenceClassification.InferenceClassificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mailFolders property</summary>
        public global::Graphdotnetv4.Users.Item.MailFolders.MailFoldersRequestBuilder MailFolders
        {
            get => new global::Graphdotnetv4.Users.Item.MailFolders.MailFoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The messages property</summary>
        public global::Graphdotnetv4.Users.Item.Messages.MessagesRequestBuilder Messages
        {
            get => new global::Graphdotnetv4.Users.Item.Messages.MessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Graphdotnetv4.Users.Item.UserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{user%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Graphdotnetv4.Users.Item.UserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{user%2Did}", rawUrl)
        {
        }
    }
}
